#!/usr/bin/env ruby
require 'optparse'
require File.expand_path('thyme', File.dirname(__FILE__))

$0 = 'thyme'
ARGV.options do |o|
  thyme = Thyme.new
  thyme.load_config
  o.set_summary_indent('  ')
  o.banner =    "Usage: #{File.basename($0)} [OPTION]"
  o.define_head "Timer for Pomodoro Technique"
  o.on('-d', '--daemon', 'run in background') { thyme.daemonize! }
  o.on('-h', '--help', 'show this help message') { puts o; exit }
  o.on('-s', '--stop', 'stops timer') { thyme.stop; exit }
  o.parse!
  thyme.run
end
